name: Bug Report
description: Report a bug in rs-tfhe
title: "[BUG] "
labels: ["bug", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened.
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: code-example
    attributes:
      label: Code Example
      description: If applicable, add code to help explain your problem.
      placeholder: |
        ```rust
        // Your code here
        ```
      render: rust

  - type: dropdown
    id: rust-version
    attributes:
      label: Rust Version
      description: What version of Rust are you using?
      options:
        - "1.70.0"
        - "1.71.0"
        - "1.72.0"
        - "1.73.0"
        - "1.74.0"
        - "1.75.0"
        - "nightly"
        - "Other (please specify)"
    validations:
      required: true

  - type: dropdown
    id: features-used
    attributes:
      label: Features Used
      description: Which features were enabled when the bug occurred?
      multiple: true
      options:
        - "default"
        - "bootstrapping"
        - "lut-bootstrap"
        - "fft_avx"
        - "fft_fma"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your environment details
      placeholder: |
        - OS: [e.g. Ubuntu 22.04, macOS 13.0, Windows 11]
        - Architecture: [e.g. x86_64, aarch64]
        - Compiler: [e.g. rustc 1.75.0]
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: Any additional information that might be helpful...
